force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <description>customer profile object</description>
    <label>Customer_c</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>LN-{0000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan&apos;s</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Customer_c__c.field-meta.xml
<CustomField>
    <fullName>Customer_c__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Loan&apos;s</relationshipLabel>
    <relationshipName>Loan_s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/EMI_Amount__c.field-meta.xml
<CustomField>
    <fullName>EMI_Amount__c</fullName>
    <formula>IF(
    Interest_Rate__c = 0,
    Loan_Amount__c / Tenure__c,
    (
        Loan_Amount__c *
        (Interest_Rate__c / 12) *
        EXP(
            Tenure__c *
            LN(1 + (Interest_Rate__c / 12))
        )
    )
    /
    (
        EXP(
            Tenure__c *
            LN(1 + (Interest_Rate__c / 12))
        ) - 1
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EMI_Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>Loan_Status__c</fullName>
    <label>Loan Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Defaulted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Tenure__c.field-meta.xml
<CustomField>
    <fullName>Tenure__c</fullName>
    <inlineHelpText>in months values like (3,6,9,12,18,24)</inlineHelpText>
    <label>Tenure</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Total_Interest__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest__c</fullName>
    <formula>Total_Payable_Amount__c - Loan_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Total_Payable_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Payable_Amount__c</fullName>
    <formula>EMI_Amount__c * Tenure__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Payable Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <label>Loan</label>
</RecordType>

force-app/main/default/classes/LoanStatementController.cls
/**
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 * Class Name      : LoanStatementController
 * Author          : <YourName>
 * Created Date    : Aug 24, 2026
 * Last Modified By: <YourName>
 * Last Modified On: Aug 24, 2026
 * Description     : This class implements for......
 *  
 * Change History  :
 *  Date          │   Author     │   Change
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 *  Aug 24, 2026  │ <YourName>   │ Initial version
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 */
public with sharing class LoanStatementController {

    public Loan__c loan { get; set; }

    public LoanStatementController() {
        Id loanId = ApexPages.currentPage().getParameters().get('id');

        if (loanId != null) {
            loan = [
                SELECT Id,
                       Name,
                       Customer_c__r.Name,
                       Loan_Amount__c,
                       Interest_Rate__c,
                       Tenure__c,
                       EMI_Amount__c,
                       Total_Payable_Amount__c,
                       Total_Interest__c,
                       Loan_Status__c,
                       Start_Date__c,
                       End_Date__c
                FROM Loan__c
                WHERE Id = :loanId
                LIMIT 1
            ];
        }
    }
}