force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Enrolled_Student__c.field-meta.xml
<CustomField>
    <fullName>Enrolled_Student__c</fullName>
    <label>Enrolled Student</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/student__c/student__c.object-meta.xml
<CustomObject>
    <label>student</label>
    <nameField>
        <label>student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/student__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>students</relationshipLabel>
    <relationshipName>students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/StudentTriggerHandler.cls
public class StudentTriggerHandler{
    public static void updateCourseCount(List<Student__c> newList,List<Student__c> oldList){
        Set<Id> courseIds = new Set<Id>();
        if (newList != null) {
            for (Student__c s : newList) {
                if (s.Course__c != null)
                    courseIds.add(s.Course__c);
            }
            System.debug('my coursestudentcount trigger is working');
        }
        if (oldList != null) {
            for (Student__c s : oldList) {
                if (s.Course__c != null)
                    courseIds.add(s.Course__c);
            }
        }
        Map<Id, Course__c> courses = new Map<Id, Course__c>(
            [SELECT Id, Enrolled_Student__c
             FROM Course__c
             WHERE Id IN :courseIds]
        );
        if (Trigger.isInsert) {
            for (Student__c s : newList) {
                if (s.Course__c != null) {
                    courses.get(s.Course__c).Enrolled_Student__c++;
                }
            }
        }
        if (Trigger.isDelete) {
            for (Student__c s : oldList) {
                if (s.Course__c != null &&
                    courses.get(s.Course__c).Enrolled_Student__c > 0) {

                    courses.get(s.Course__c).Enrolled_Student__c--;
                }
            }
        }
        if (Trigger.isUpdate) {
            for (Integer i = 0; i < newList.size(); i++) {
                if (newList[i].Course__c != oldList[i].Course__c) {
                    if (oldList[i].Course__c != null &&
                        courses.get(oldList[i].Course__c).Enrolled_Student__c > 0) {
                        courses.get(oldList[i].Course__c).Enrolled_Student__c--;
                    }
                    if (newList[i].Course__c != null) {
                        courses.get(newList[i].Course__c).Enrolled_Student__c++;
                    }
                }
            }
        }
        update courses.values();
    }
}