force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/student__c/student__c.object-meta.xml
<CustomObject>
    <label>student</label>
    <nameField>
        <label>student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/student__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>students</relationshipLabel>
    <relationshipName>students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/student__c/fields/Percentage__c.field-meta.xml
<CustomField>
    <fullName>Percentage__c</fullName>
    <label>Percentage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/studentExtension.cls
public class studentExtension{
    public Student__c student{get;set;}
    //public Course__c Course;
    public StudentExtension(ApexPages.StandardController sc){
        //student=(Student__c)controller.getRecord();
        //course=(Course__c)controller.getRecord();
         Id studentId = sc.getId();
        //student = [Select Id,Percentage__c,Course__c,Course__r.Duration__c from Student__c where Id = :controller.getId()];
               student = [SELECT Id, Name, Percentage__c,Course__r.Duration__c FROM Student__c WHERE Id = :studentId ];
    }
    public String getWelcomeMessage(){
        return 'Welcome to ABC Training Institute';
    }
    public String getGrade(){
        if(student.Percentage__c>=90)
            return ' Grade: A';
        else if(student.Percentage__c>=75)
            return 'Grade: B';
        else if(student.Percentage__c>=60)
            return 'Grade:C';
        else
            return 'Grade:D';
    }
    public String getScholarshipStatus(){
        if(student.Percentage__c>=85)
            return 'Scholarship: Eligible';
        return 'Scholarship: Not Eligible';
    }
    
    public String getCourseCategory() {
    if(student.Course__r.Duration__c > 8)
        return 'Advanced';
    return 'Standard';
    }
}