force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Fee__c.field-meta.xml
<CustomField>
    <fullName>Fee__c</fullName>
    <label>Course Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CustomStudentController.cls
public class CustomStudentController{
    public String selectedCourseId{get;set;}
    public Course__c selectedCourse{get;set;}
    public List<SelectOption> courseOptions {get;set;}
    public CustomStudentController(){
        courseOptions = new List<SelectOption>();
        for(Course__c c :[SELECT Id, Name FROM Course__c]){
            courseOptions.add(
                new SelectOption(c.Id, c.Name)
            );
        }
    }
    public PageReference showCourse(){
        selectedCourse = [SELECT Fee__c, Duration__c FROM Course__c WHERE Id = :selectedCourseId];
        return null;
    }
    public PageReference registerStudent(){
        ApexPages.addMessage(
            new ApexPages.Message(
                ApexPages.Severity.CONFIRM,
                'Student successfully registered.'
            )
        );
        return null;
    }

}