force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>LN-{0000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan&apos;s</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/EMI_Amount__c.field-meta.xml
<CustomField>
    <fullName>EMI_Amount__c</fullName>
    <formula>IF(
    Interest_Rate__c = 0,
    Loan_Amount__c / Tenure__c,
    (
        Loan_Amount__c *
        (Interest_Rate__c / 12) *
        EXP(
            Tenure__c *
            LN(1 + (Interest_Rate__c / 12))
        )
    )
    /
    (
        EXP(
            Tenure__c *
            LN(1 + (Interest_Rate__c / 12))
        ) - 1
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EMI_Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Tenure__c.field-meta.xml
<CustomField>
    <fullName>Tenure__c</fullName>
    <inlineHelpText>in months values like (3,6,9,12,18,24)</inlineHelpText>
    <label>Tenure</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Total_Interest__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest__c</fullName>
    <formula>Total_Payable_Amount__c - Loan_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Total_Payable_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Payable_Amount__c</fullName>
    <formula>EMI_Amount__c * Tenure__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Payable Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/EmiSummaryController.cls
public with sharing class EmiSummaryController {

    @AuraEnabled(cacheable=true)
    public static Loan__c getEmiSummary() {

        List<Loan__c> loans = [
            SELECT Id,
                   EMI_Amount__c,
                   Total_Payable_Amount__c,
                   Total_Interest__c,
                   Tenure__c
            FROM Loan__c
            LIMIT 1
        ];

        return loans.isEmpty() ? null : loans[0];
    }
}